name: Run tests 

on:
  push:
    branches: ['main']

jobs:
  run-test:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository code
        uses: actions/checkout@v4

      - name: Install proper version of NodeJS
        uses: actions/setup-node@v6
        with: 
          node-version-file: package.json

      - name: Check currently used NodeJS version
        run: node --version

      - name: Install dependencies
        run: yarn install --frozen-lockfile

      - name: Run tests
        run: yarn test
